
[advisories]
ignore = []
notice = "deny"
unmaintained = "warn"
vulnerability = "deny"
yanked = "deny"

# This library uses the MPL-2 license.
#
# See https://www.mozilla.org/en-US/MPL/2.0/permissive-code-into-mpl/
[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
    "MPL-2.0",
    "Unicode-DFS-2016",
]
default = "deny"
confidence-threshold = 1.0
unlicensed = "deny"

[bans]
allow = []
deny = [
    # License is non-trivial
    { name = "ring" },
]
multiple-versions = "warn"
skip = []
skip-tree = [
    # Redox is an obscure, Rust-based operating system
    { name = "redox_syscall" },
    # simple-logger is on an old version
    { name = "windows-sys" }
]
wildcards = "deny"

[sources]
allow-git = []
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
unknown-git = "deny"
unknown-registry = "deny"

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
