name: ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deny:
    name: Cargo deny
    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-20.04
          - windows-2022
        toolchain:
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo install cargo-deny
      - run: cargo deny check
    timeout-minutes: 30

  test-mac:
    name: Cargo test on Mac
    strategy:
      # Only have one Mac build because Mac build setup is flaky
      matrix:
        os:
          - macOS-latest
        toolchain:
          - 1.64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          components: clippy
          toolchain: ${{ matrix.toolchain }}
      - run: cargo clippy
      - run: cargo test --no-run
      - run: cargo test --no-fail-fast
    timeout-minutes: 45

  test-nix:
    name: Cargo test on nix
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        toolchain:
          - 1.64
          - beta
          - nightly
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          components: clippy
          toolchain: ${{ matrix.toolchain }}
      - run: docker version
      - run: cargo clippy
      - run: cargo test --no-run
      - run: cargo test --no-fail-fast
    timeout-minutes: 30

  test-windows:
    name: Cargo test on Windows
    strategy:
      matrix:
        os:
          - windows-2022
        toolchain:
          - 1.64
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      # See https://docs.rs/crate/openssl-sys/0.9.36
      - run: vcpkg install openssl:x64-windows-static-md
      - run: vcpkg integrate install
      - run: cargo test --no-run
      - run: cargo test --no-fail-fast
    timeout-minutes: 45
